/**
 * Generate human-readable Markdown views of the machine-readable registries.
 * The JSON under specs/ is the source of truth; these files are views only.
 *
 *   node scripts/generate-spec-docs.ts [--check]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  CapabilityLedger,
  DomainRegistry,
  InvariantRegistry,
  PhaseRegistry,
} from "@harness/traceability";

const root = join(import.meta.dirname, "..");
const outDir = join(root, "docs", "generated");
const check = process.argv.includes("--check");
const load = <T>(p: string): T => JSON.parse(readFileSync(join(root, p), "utf8")) as T;
const header = (title: string, source: string) =>
  `<!-- GENERATED by scripts/generate-spec-docs.ts from ${source}. Do not edit; edit the JSON. -->\n\n# ${title}\n\n`;
const cell = (s: string) => s.replaceAll("|", "\\|").replaceAll("\n", " ");
const list = (v: string[] | null) =>
  v === null ? "_pending (not yet specified)_" : v.length ? v.join(", ") : "—";

const domains = load<DomainRegistry>("specs/domains/domains.json");
const invariants = load<InvariantRegistry>("specs/invariants/invariants.json");
const phases = load<PhaseRegistry>("specs/phases/phases.json");
const ledgerPath = "specs/capabilities/ledger.json";

const files: Record<string, string> = {
  "domains.md":
    header("Architecture domains", "specs/domains/domains.json") +
    `Source: ${domains.source}\n\n| ID | Domain | Responsibility |\n|---|---|---|\n` +
    domains.domains.map((d) => `| ${d.id} | ${cell(d.name)} | ${cell(d.responsibility)} |`).join("\n") +
    "\n",
  "invariants.md":
    header("Architectural invariants", "specs/invariants/invariants.json") +
    "| ID | Invariant | P00 scope | P00 references | Notes |\n|---|---|---|---|---|\n" +
    invariants.invariants
      .map(
        (i) =>
          `| ${i.id} | ${cell(i.statement)} | ${i.p00_scope} | ${i.p00_refs.map((r) => `\`${cell(r)}\``).join("<br>") || "—"} | ${cell(i.notes) || "—"} |`,
      )
      .join("\n") +
    "\n",
  "phases.md":
    header("Phase registry (P00–P18)", "specs/phases/phases.json") +
    `Source: ${phases.source}\n\n| Phase | Purpose | Status | Prerequisites | Owned capabilities | Entry criteria | Exit criteria |\n|---|---|---|---|---|---|---|\n` +
    phases.phases
      .map(
        (p) =>
          `| ${p.id} | ${cell(p.purpose)} | ${p.status} | ${list(p.prerequisites)} | ${list(p.owned_capability_ids)} | ${p.entry_criteria === null ? list(null) : `${p.entry_criteria.length} item(s)`} | ${p.exit_criteria === null ? list(null) : `${p.exit_criteria.length} item(s)`} |`,
      )
      .join("\n") +
    "\n",
  "capabilities.md": existsSync(join(root, ledgerPath))
    ? header("Capability ledger (C001–C168)", ledgerPath) +
      "| ID | Title | Domain | Phase | Mandatory | Status | Dependencies |\n|---|---|---|---|---|---|---|\n" +
      load<CapabilityLedger>(ledgerPath)
        .capabilities.map(
          (c) =>
            `| ${c.id} | ${cell(c.title)} | ${c.domain} | ${c.owning_phase} | ${c.mandatory ? "yes" : "no"} | ${c.status} | ${c.dependencies.join(", ") || "—"} |`,
        )
        .join("\n") +
      "\n"
    : `${header("Capability ledger (C001–C168)", ledgerPath)}**BLOCKED (P00-BLK-001):** the authoritative capability catalog has not been provided. C001–C168 are reserved; no records exist. See \`specs/capabilities/README.md\`.\n`,
};

const stale: string[] = [];
mkdirSync(outDir, { recursive: true });
for (const [name, content] of Object.entries(files)) {
  const path = join(outDir, name);
  const current = existsSync(path) ? readFileSync(path, "utf8").replaceAll("\r\n", "\n") : undefined;
  if (current === content) continue;
  if (check) stale.push(name);
  else writeFileSync(path, content);
}
if (stale.length) {
  console.error(`stale generated docs: ${stale.join(", ")} (run node scripts/generate-spec-docs.ts)`);
  process.exit(1);
}
console.log(
  check ? "generated docs up to date" : `generated ${Object.keys(files).length} views in docs/generated`,
);
